### ISSUE TITLE
Стенка на стенку

### ISSUE THREAD

**Issue by AppLoidx** [tolikttaaa/Algo_and_DS#3]
Решения в любом случае приводится к перемножению. Докажем, что значения чисел должны быть равномерными, не рассматривая частные случаи:

Пусть будет какая-то последовательность:

... * `b` * `b+k` * ... = c * `b^2 + bk` , где `c` - перемножение других чисел

Сравним его с тем же рядом, но перенесем одно значение из `b+k` на `b`:

... * `b + 1` * `b+k-1` * ... = `b^2 + bk + k - 1`

`b^2 + bk + k - 1` **vs** `b^2 + bk`

`k - 1` **vs** `0`

Отсюда видно, что при k=1 изменений не будет, а при k=2 результат увеличится

С другой стороны, также можно сказать, что при k = 0, результат противоположный

По сути то же самое решение, только формулы более удобочитаемые (без `x/2`)

**Comment by tolikttaaa** [comment]
Можно и так, как альтернативное доказательство, но то мне нравится больше, так как если его реализовывать, то система быстрее уравнивается.
